# Generated by Django 6.1 on 2026-09-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_section'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RailwaySection',
        ),
    ]
