# Generated by Django 6.1 on 2026-09-02 14:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corridors', '0001_initial'),
        ('trains', '0002_delete_railwaysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('train_type', models.CharField(choices=[('PASSENGER', 'Passenger'), ('EXPRESS', 'Express'), ('RAJDHANI', 'Rajdhani'), ('VB', 'Vande Bharat'), ('SHATABDI', 'Shatabdi'), ('FREIGHT', 'Freight')], max_length=20)),
                ('priority', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='TrainMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_movements', to='corridors.railwaysection')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='trains.train')),
            ],
        ),
    ]
