# Generated by Django 6.1 on 2026-09-03 06:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridors', '0001_initial'),
        ('trains', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainmovement',
            name='entry_time',
        ),
        migrations.RemoveField(
            model_name='trainmovement',
            name='exit_time',
        ),
        migrations.RemoveField(
            model_name='trainmovement',
            name='section',
        ),
        migrations.RemoveField(
            model_name='trainmovement',
            name='train',
        ),
        migrations.AddField(
            model_name='trainmovement',
            name='actual_entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainmovement',
            name='actual_exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainmovement',
            name='service_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_entry_time', models.TimeField()),
                ('scheduled_exit_time', models.TimeField()),
                ('running_days', models.CharField(default='1111111', max_length=7, validators=[django.core.validators.RegexValidator(message='running_days must contain exactly 7 characters of 0 or 1.', regex='^[01]{7}$')])),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_schedules', to='corridors.railwaysection')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trains.train')),
            ],
        ),
        migrations.AddField(
            model_name='trainmovement',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='trains.trainschedule'),
        ),
        migrations.AddIndex(
            model_name='trainmovement',
            index=models.Index(fields=['schedule', 'service_date'], name='trains_trai_schedul_a40756_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainmovement',
            constraint=models.UniqueConstraint(fields=('schedule', 'service_date'), name='unique_train_movement_per_day'),
        ),
    ]
