# Generated by Django 6.1 on 2026-09-03 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_remove_trainmovement_entry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainschedule',
            name='scheduled_exit_day_offset',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trainmovement',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='trains.trainschedule'),
        ),
    ]

