# Generated by Django 6.1 on 2026-09-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0005_trainschedule_scheduled_exit_day_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainmovement',
            name='delay_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainmovement',
            name='estimated_entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainmovement',
            name='estimated_exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainmovement',
            name='last_live_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainmovement',
            name='status_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
