# Generated by Django 6.1 on 2026-09-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corridors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=20)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_windows', to='corridors.railwaysection')),
            ],
        ),
    ]
