# Generated by Django 6.1 on 2026-09-07 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('maintenance', '0002_alter_maintenancetask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockwindow',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_windows', to='maintenance.maintenancetask'),
        ),
    ]
