# Generated by Django 6.1 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_alter_maintenancetask_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetask",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="cancellation_remark",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="completion_remark",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="start_checklist",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="maintenancetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SCHEDULED", "Scheduled"),
                    ("ACTIVE", "Active"),
                    ("DELAYED", "Delayed"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
