# Generated by Django 6.1 on 2026-09-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_maintenance_execution_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_code", models.CharField(db_index=True, max_length=100)),
                ("event", models.CharField(choices=[("CREATED", "Created"), ("UPDATED", "Updated"), ("SCHEDULED", "Scheduled"), ("STARTED", "Started"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled"), ("DELAYED", "Delayed"), ("DELETED", "Deleted")], max_length=20)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("SCHEDULED", "Scheduled"), ("ACTIVE", "Active"), ("DELAYED", "Delayed"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled")], max_length=20)),
                ("remark", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="logs", to="maintenance.maintenancetask")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
