# Generated by Django 6.1 on 2026-09-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
