# Generated by Codex on 2026-09-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0003_alter_blockwindow_task"),
        ("maintenance", "0005_maintenancetask_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("status", models.CharField(choices=[("PROPOSED", "Proposed"), ("SCHEDULED", "Scheduled"), ("ACTIVE", "Active"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled")], default="PROPOSED", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("block_window", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="maintenance_batch", to="blocks.blockwindow")),
                ("section", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="maintenance_batches", to="corridors.railwaysection")),
                ("tasks", models.ManyToManyField(related_name="maintenance_batches", to="maintenance.maintenancetask")),
            ],
        ),
    ]
