# Generated by Codex on 2026-09-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blocks", "0003_alter_blockwindow_task"),
        ("maintenance", "0006_maintenancebatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancetask",
            name="shared_block_window",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_maintenance_tasks",
                to="blocks.blockwindow",
            ),
        ),
    ]
