# Generated by Django 6.1 on 2026-09-02 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('SNT', 'Signal & Telecom'), ('TRACTION', 'Traction')], max_length=20)),
                ('criticality', models.PositiveIntegerField()),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='trains.railwaysection')),
            ],
        ),
    ]
