# Generated by Django 6.1 on 2026-09-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('corridors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='corridors.railwaysection'),
        ),
    ]
