# Generated by Django 6.1 on 2026-09-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwaysection',
            name='destination_station_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='railwaysection',
            name='source_station_code',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
    ]
